# Generated by Django 5.0.6 on 2024-07-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_persona_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('subtema', models.CharField(blank=True, max_length=100, null=True)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsChat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_type', models.CharField(max_length=50)),
                ('chat_description', models.TextField()),
                ('chat_date', models.DateTimeField(auto_now_add=True)),
                ('chat_pregunta', models.TextField()),
                ('chat_respuesta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanesGtd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.knowledgebase')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoGtd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SucursalGtd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='planesgtd',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productogtd'),
        ),
        migrations.AddField(
            model_name='logschat',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productogtd'),
        ),
        migrations.AddField(
            model_name='logschat',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursalgtd'),
        ),
    ]
